use_default_settings: true

general:
  debug: false
  instance_name: "Private Research SearXNG"

search:
  safe_search: 1
  autocomplete: ""
  ban_time_on_fail: 10
  max_ban_time_on_fail: 60
  suspended_times:
    SearxEngineAccessDenied: 300
    SearxEngineCaptcha: 600
    SearxEngineTooManyRequests: 120
    cf_SearxEngineCaptcha: 1800
    cf_SearxEngineAccessDenied: 600
    recaptcha_SearxEngineCaptcha: 1800
  formats:
    - html
    - json

engines:
  - name: bing
    disabled: false
  - name: mojeek
    disabled: false
  - name: presearch
    disabled: false
  - name: qwant
    disabled: false
  - name: yahoo
    disabled: false
  - name: microsoft learn
    disabled: false
  - name: crossref
    disabled: false
  - name: openalex
    disabled: false

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "${SEARXNG_SECRET}"
  limiter: false
  image_proxy: false
  method: "GET"

outgoing:
  request_timeout: 15.0
  max_request_timeout: 30.0
  enable_http2: false
  proxies:
    all://:
      - socks5h://tor-search:9050

ui:
  static_use_hash: true
  query_in_title: false

enabled_plugins:
  - "Hash plugin"
  - "Self Information"
  - "Tracker URL remover"
